name: 🐞 Rapportera ett fel
description: Skapa en rapport för att hjälpa oss att rätta till felet.
labels: 'bug'
body:
  - type: markdown
    attributes:
      value: |
        Tack för att du tar dig tid att fylla i den här felrapporten!
  - type: textarea
    id: bug-description
    attributes:
      label: Beskriv felet
      description: En tydlig och kortfattad beskrivning av vad felet är. Om du tänker skicka in en PR för det här problemet, berätta för oss i beskrivningen. Tack!
      placeholder: Beskrivning
    validations:
      required: true
  - type: input
    id: reproduction
    attributes:
      label: Hur uppstår felet
      description: En [minimal beskrivning](https://stackoverflow.com/help/minimal-reproducible-example) är **obligatorisk**, annars kan problemet avslutas utan ytterligare meddelande. [**Varför och hur?**](https://antfu.me/posts/why-reproductions-are-required)
      placeholder: Beskrivning
    validations:
      required: true
  - type: textarea
    id: system-info
    attributes:
      label: Systeminformation
      description: Om du har möjlighet kan du skriva följande kommando i terminalen på din dator `npx envinfo --system --binaries --browsers` och klistra in resultatet
      render: Shell
      placeholder: Operativsystem, Webbläsare mm
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: Övrig information
      description: Fyll i annan information som kan vara bra att känna till för att fixa felet
      render: Shell
      placeholder: Övrigt...
    validations:
      required: false
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Bekräftelser
      description: Se till att du gör följande innan du skickar in problemet
      options:
        - label: Följ vår [uppförandekod](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md).
          required: true
        - label: Kontrollera att det inte redan finns ett problem som rapporterar samma bugg för att undvika att skapa en dubblett.
          required: true
        - label: Kontrollera att detta är en konkret bugg. För frågor och svar, öppna en GitHub-diskussion istället.
          required: true
        - label: Beskrivningen är en komplett beskrivning hur felet uppstår.
          required: true
