name: 游 Ny funktion
description: Har du en id칠 eller saknar n친gon funktion
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Tack f칬r ditt intresse f칬r projektet och att du tog dig tid att fylla i denna funktionsrapport!
  - type: textarea
    id: feature-description
    attributes:
      label: Tydlig och kortfattad beskrivning av problemet
      description: 'Som en anv칛ndare av applikationen skulle jag vilja kunna [칬nskning] f칬r att [f칬rdel/m친l]'
    validations:
      required: true
  - type: textarea
    id: suggested-solution
    attributes:
      label: F칬reslagen l칬sning
      description: 'P친 sidan [xy] kan vi tillhandah친lla f칬ljande implementering...'
    validations:
      required: true
  - type: textarea
    id: alternative
    attributes:
      label: Alternativ
      description: Tydlig och koncis beskrivning av eventuella alternativa l칬sningar eller funktioner du har 칬verv칛gt.
  - type: textarea
    id: additional-context
    attributes:
      label: Ytterligare information
      description: Eventuellt annat information eller sk칛rmdumpar om funktionsbeg칛ran h칛r.
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Bekr칛ftelser
      description: Se till att du g칬r f칬ljande innan du skickar in din beg칛ran
      options:
        - label: F칬lj v친r [uppf칬randekod](https://github.com/bjorkgard/.github/blob/main/CODE_OF_CONDUCT.md)
          required: true
        - label: Kontrollera att det inte redan finns en f칬rfr친gan som beg칛r samma funktion f칬r att undvika att skapa en dubblett.
          required: true
