name: 游 Felstavningar / 칬vers칛ttning
description: Vill du hj칛lpa till med att fixa stavfel eller 칬vers칛tta applikationen s친 칛r du v칛lkommen!
labels: []
body:
  - type: markdown
    attributes:
      value: |
        All textbearbetning sker utanf칬r applikationen i en webbbaserad milj칬. Vill du vara med och hj칛lpa till med textjusteringar eller 칬vers칛tta applikationen till andra spr친k 칛r du v칛lkommen att kontakta utvecklarna f칬r att f친 tillg친ng till texterna.
        
        Om du ist칛llet bara vill rapportera in ett textfel kan du g칬ra det i textf칛ltet nedan. 
  - type: textarea
    id: context
    attributes:
      label: Information
